
export const CacheTabTypeEnum = {
    API_TEST_API_TABLE: 'API_TEST_API_TABLE',
    API_TEST_CASE_TABLE: 'API_TEST_CASE_TABLE',
    API_TEST_MOCK_TABLE: 'API_TEST_MOCK_TABLE',
    API_SCENARIO_TABLE: 'API_SCENARIO_TABLE',
    CASE_MANAGEMENT_TABLE_FILTER: 'CASE_MANAGEMENT_TABLE_FILTER',
} as const;
export default {};
